(cl:defpackage arducam_usb2_ros-srv
  (:use )
  (:export
   "CAPTURE"
   "<CAPTURE-REQUEST>"
   "CAPTURE-REQUEST"
   "<CAPTURE-RESPONSE>"
   "CAPTURE-RESPONSE"
   "READREG"
   "<READREG-REQUEST>"
   "READREG-REQUEST"
   "<READREG-RESPONSE>"
   "READREG-RESPONSE"
   "TRIGGER"
   "<TRIGGER-REQUEST>"
   "TRIGGER-REQUEST"
   "<TRIGGER-RESPONSE>"
   "TRIGGER-RESPONSE"
   "WRITEREG"
   "<WRITEREG-REQUEST>"
   "WRITEREG-REQUEST"
   "<WRITEREG-RESPONSE>"
   "WRITEREG-RESPONSE"
  ))

