// Generated by gencpp from file arducam_usb2_ros/CaptureResponse.msg
// DO NOT EDIT!


#ifndef ARDUCAM_USB2_ROS_MESSAGE_CAPTURERESPONSE_H
#define ARDUCAM_USB2_ROS_MESSAGE_CAPTURERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arducam_usb2_ros
{
template <class ContainerAllocator>
struct CaptureResponse_
{
  typedef CaptureResponse_<ContainerAllocator> Type;

  CaptureResponse_()
    : response()  {
    }
  CaptureResponse_(const ContainerAllocator& _alloc)
    : response(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::arducam_usb2_ros::CaptureResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arducam_usb2_ros::CaptureResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CaptureResponse_

typedef ::arducam_usb2_ros::CaptureResponse_<std::allocator<void> > CaptureResponse;

typedef boost::shared_ptr< ::arducam_usb2_ros::CaptureResponse > CaptureResponsePtr;
typedef boost::shared_ptr< ::arducam_usb2_ros::CaptureResponse const> CaptureResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arducam_usb2_ros::CaptureResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arducam_usb2_ros::CaptureResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arducam_usb2_ros::CaptureResponse_<ContainerAllocator1> & lhs, const ::arducam_usb2_ros::CaptureResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arducam_usb2_ros::CaptureResponse_<ContainerAllocator1> & lhs, const ::arducam_usb2_ros::CaptureResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arducam_usb2_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::arducam_usb2_ros::CaptureResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arducam_usb2_ros::CaptureResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arducam_usb2_ros::CaptureResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arducam_usb2_ros::CaptureResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arducam_usb2_ros::CaptureResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arducam_usb2_ros::CaptureResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arducam_usb2_ros::CaptureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6de314e2dc76fbff2b6244a6ad70b68d";
  }

  static const char* value(const ::arducam_usb2_ros::CaptureResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6de314e2dc76fbffULL;
  static const uint64_t static_value2 = 0x2b6244a6ad70b68dULL;
};

template<class ContainerAllocator>
struct DataType< ::arducam_usb2_ros::CaptureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arducam_usb2_ros/CaptureResponse";
  }

  static const char* value(const ::arducam_usb2_ros::CaptureResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arducam_usb2_ros::CaptureResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string response\n"
"\n"
;
  }

  static const char* value(const ::arducam_usb2_ros::CaptureResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arducam_usb2_ros::CaptureResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CaptureResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arducam_usb2_ros::CaptureResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arducam_usb2_ros::CaptureResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARDUCAM_USB2_ROS_MESSAGE_CAPTURERESPONSE_H
