// Generated by gencpp from file arducam_usb2_ros/ReadReg.msg
// DO NOT EDIT!


#ifndef ARDUCAM_USB2_ROS_MESSAGE_READREG_H
#define ARDUCAM_USB2_ROS_MESSAGE_READREG_H

#include <ros/service_traits.h>


#include <arducam_usb2_ros/ReadRegRequest.h>
#include <arducam_usb2_ros/ReadRegResponse.h>


namespace arducam_usb2_ros
{

struct ReadReg
{

typedef ReadRegRequest Request;
typedef ReadRegResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReadReg
} // namespace arducam_usb2_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arducam_usb2_ros::ReadReg > {
  static const char* value()
  {
    return "d68ea0117c09efb9a8ad3a62738f7b29";
  }

  static const char* value(const ::arducam_usb2_ros::ReadReg&) { return value(); }
};

template<>
struct DataType< ::arducam_usb2_ros::ReadReg > {
  static const char* value()
  {
    return "arducam_usb2_ros/ReadReg";
  }

  static const char* value(const ::arducam_usb2_ros::ReadReg&) { return value(); }
};


// service_traits::MD5Sum< ::arducam_usb2_ros::ReadRegRequest> should match
// service_traits::MD5Sum< ::arducam_usb2_ros::ReadReg >
template<>
struct MD5Sum< ::arducam_usb2_ros::ReadRegRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arducam_usb2_ros::ReadReg >::value();
  }
  static const char* value(const ::arducam_usb2_ros::ReadRegRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arducam_usb2_ros::ReadRegRequest> should match
// service_traits::DataType< ::arducam_usb2_ros::ReadReg >
template<>
struct DataType< ::arducam_usb2_ros::ReadRegRequest>
{
  static const char* value()
  {
    return DataType< ::arducam_usb2_ros::ReadReg >::value();
  }
  static const char* value(const ::arducam_usb2_ros::ReadRegRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arducam_usb2_ros::ReadRegResponse> should match
// service_traits::MD5Sum< ::arducam_usb2_ros::ReadReg >
template<>
struct MD5Sum< ::arducam_usb2_ros::ReadRegResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arducam_usb2_ros::ReadReg >::value();
  }
  static const char* value(const ::arducam_usb2_ros::ReadRegResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arducam_usb2_ros::ReadRegResponse> should match
// service_traits::DataType< ::arducam_usb2_ros::ReadReg >
template<>
struct DataType< ::arducam_usb2_ros::ReadRegResponse>
{
  static const char* value()
  {
    return DataType< ::arducam_usb2_ros::ReadReg >::value();
  }
  static const char* value(const ::arducam_usb2_ros::ReadRegResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARDUCAM_USB2_ROS_MESSAGE_READREG_H
