// Generated by gencpp from file arducam_usb2_ros/Trigger.msg
// DO NOT EDIT!


#ifndef ARDUCAM_USB2_ROS_MESSAGE_TRIGGER_H
#define ARDUCAM_USB2_ROS_MESSAGE_TRIGGER_H

#include <ros/service_traits.h>


#include <arducam_usb2_ros/TriggerRequest.h>
#include <arducam_usb2_ros/TriggerResponse.h>


namespace arducam_usb2_ros
{

struct Trigger
{

typedef TriggerRequest Request;
typedef TriggerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Trigger
} // namespace arducam_usb2_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arducam_usb2_ros::Trigger > {
  static const char* value()
  {
    return "6de314e2dc76fbff2b6244a6ad70b68d";
  }

  static const char* value(const ::arducam_usb2_ros::Trigger&) { return value(); }
};

template<>
struct DataType< ::arducam_usb2_ros::Trigger > {
  static const char* value()
  {
    return "arducam_usb2_ros/Trigger";
  }

  static const char* value(const ::arducam_usb2_ros::Trigger&) { return value(); }
};


// service_traits::MD5Sum< ::arducam_usb2_ros::TriggerRequest> should match
// service_traits::MD5Sum< ::arducam_usb2_ros::Trigger >
template<>
struct MD5Sum< ::arducam_usb2_ros::TriggerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arducam_usb2_ros::Trigger >::value();
  }
  static const char* value(const ::arducam_usb2_ros::TriggerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arducam_usb2_ros::TriggerRequest> should match
// service_traits::DataType< ::arducam_usb2_ros::Trigger >
template<>
struct DataType< ::arducam_usb2_ros::TriggerRequest>
{
  static const char* value()
  {
    return DataType< ::arducam_usb2_ros::Trigger >::value();
  }
  static const char* value(const ::arducam_usb2_ros::TriggerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arducam_usb2_ros::TriggerResponse> should match
// service_traits::MD5Sum< ::arducam_usb2_ros::Trigger >
template<>
struct MD5Sum< ::arducam_usb2_ros::TriggerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arducam_usb2_ros::Trigger >::value();
  }
  static const char* value(const ::arducam_usb2_ros::TriggerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arducam_usb2_ros::TriggerResponse> should match
// service_traits::DataType< ::arducam_usb2_ros::Trigger >
template<>
struct DataType< ::arducam_usb2_ros::TriggerResponse>
{
  static const char* value()
  {
    return DataType< ::arducam_usb2_ros::Trigger >::value();
  }
  static const char* value(const ::arducam_usb2_ros::TriggerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARDUCAM_USB2_ROS_MESSAGE_TRIGGER_H
