// Generated by gencpp from file arducam_usb2_ros/WriteRegRequest.msg
// DO NOT EDIT!


#ifndef ARDUCAM_USB2_ROS_MESSAGE_WRITEREGREQUEST_H
#define ARDUCAM_USB2_ROS_MESSAGE_WRITEREGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arducam_usb2_ros
{
template <class ContainerAllocator>
struct WriteRegRequest_
{
  typedef WriteRegRequest_<ContainerAllocator> Type;

  WriteRegRequest_()
    : register(0)
    , value(0)  {
    }
  WriteRegRequest_(const ContainerAllocator& _alloc)
    : register(0)
    , value(0)  {
  (void)_alloc;
    }



   typedef uint64_t _register_type;
  _register_type register;

   typedef uint64_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::arducam_usb2_ros::WriteRegRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arducam_usb2_ros::WriteRegRequest_<ContainerAllocator> const> ConstPtr;

}; // struct WriteRegRequest_

typedef ::arducam_usb2_ros::WriteRegRequest_<std::allocator<void> > WriteRegRequest;

typedef boost::shared_ptr< ::arducam_usb2_ros::WriteRegRequest > WriteRegRequestPtr;
typedef boost::shared_ptr< ::arducam_usb2_ros::WriteRegRequest const> WriteRegRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arducam_usb2_ros::WriteRegRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arducam_usb2_ros::WriteRegRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arducam_usb2_ros::WriteRegRequest_<ContainerAllocator1> & lhs, const ::arducam_usb2_ros::WriteRegRequest_<ContainerAllocator2> & rhs)
{
  return lhs.register == rhs.register &&
    lhs.value == rhs.value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arducam_usb2_ros::WriteRegRequest_<ContainerAllocator1> & lhs, const ::arducam_usb2_ros::WriteRegRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arducam_usb2_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::arducam_usb2_ros::WriteRegRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arducam_usb2_ros::WriteRegRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arducam_usb2_ros::WriteRegRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arducam_usb2_ros::WriteRegRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arducam_usb2_ros::WriteRegRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arducam_usb2_ros::WriteRegRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arducam_usb2_ros::WriteRegRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9e6b1001a8a9c3622da5d369f724b40a";
  }

  static const char* value(const ::arducam_usb2_ros::WriteRegRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9e6b1001a8a9c362ULL;
  static const uint64_t static_value2 = 0x2da5d369f724b40aULL;
};

template<class ContainerAllocator>
struct DataType< ::arducam_usb2_ros::WriteRegRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arducam_usb2_ros/WriteRegRequest";
  }

  static const char* value(const ::arducam_usb2_ros::WriteRegRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arducam_usb2_ros::WriteRegRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 register\n"
"uint64 value\n"
;
  }

  static const char* value(const ::arducam_usb2_ros::WriteRegRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arducam_usb2_ros::WriteRegRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.register);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WriteRegRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arducam_usb2_ros::WriteRegRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arducam_usb2_ros::WriteRegRequest_<ContainerAllocator>& v)
  {
    s << indent << "register: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.register);
    s << indent << "value: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARDUCAM_USB2_ROS_MESSAGE_WRITEREGREQUEST_H
