// Generated by gencpp from file arducam_usb2_ros/WriteRegResponse.msg
// DO NOT EDIT!


#ifndef ARDUCAM_USB2_ROS_MESSAGE_WRITEREGRESPONSE_H
#define ARDUCAM_USB2_ROS_MESSAGE_WRITEREGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arducam_usb2_ros
{
template <class ContainerAllocator>
struct WriteRegResponse_
{
  typedef WriteRegResponse_<ContainerAllocator> Type;

  WriteRegResponse_()
    : return_value()  {
    }
  WriteRegResponse_(const ContainerAllocator& _alloc)
    : return_value(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _return_value_type;
  _return_value_type return_value;





  typedef boost::shared_ptr< ::arducam_usb2_ros::WriteRegResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arducam_usb2_ros::WriteRegResponse_<ContainerAllocator> const> ConstPtr;

}; // struct WriteRegResponse_

typedef ::arducam_usb2_ros::WriteRegResponse_<std::allocator<void> > WriteRegResponse;

typedef boost::shared_ptr< ::arducam_usb2_ros::WriteRegResponse > WriteRegResponsePtr;
typedef boost::shared_ptr< ::arducam_usb2_ros::WriteRegResponse const> WriteRegResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arducam_usb2_ros::WriteRegResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arducam_usb2_ros::WriteRegResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::arducam_usb2_ros::WriteRegResponse_<ContainerAllocator1> & lhs, const ::arducam_usb2_ros::WriteRegResponse_<ContainerAllocator2> & rhs)
{
  return lhs.return_value == rhs.return_value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::arducam_usb2_ros::WriteRegResponse_<ContainerAllocator1> & lhs, const ::arducam_usb2_ros::WriteRegResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace arducam_usb2_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::arducam_usb2_ros::WriteRegResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arducam_usb2_ros::WriteRegResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arducam_usb2_ros::WriteRegResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arducam_usb2_ros::WriteRegResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arducam_usb2_ros::WriteRegResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arducam_usb2_ros::WriteRegResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arducam_usb2_ros::WriteRegResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b68c06a61da57812b519df2ba93f87ff";
  }

  static const char* value(const ::arducam_usb2_ros::WriteRegResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb68c06a61da57812ULL;
  static const uint64_t static_value2 = 0xb519df2ba93f87ffULL;
};

template<class ContainerAllocator>
struct DataType< ::arducam_usb2_ros::WriteRegResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arducam_usb2_ros/WriteRegResponse";
  }

  static const char* value(const ::arducam_usb2_ros::WriteRegResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arducam_usb2_ros::WriteRegResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string return_value\n"
"\n"
;
  }

  static const char* value(const ::arducam_usb2_ros::WriteRegResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arducam_usb2_ros::WriteRegResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.return_value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WriteRegResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arducam_usb2_ros::WriteRegResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arducam_usb2_ros::WriteRegResponse_<ContainerAllocator>& v)
  {
    s << indent << "return_value: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.return_value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARDUCAM_USB2_ROS_MESSAGE_WRITEREGRESPONSE_H
